### ISSUE TITLE
im facing module not found error.. 

### ISSUE THREAD

**Issue by AmirMGhanem** [Pinheiro-Lucas/fps-game-ursina#2]
Hi, im willing to contribute to the project, but im facing 
 ModuleNotFoundError: No module named 'screeninfo'

**Comment by pinheiro-lucas** [comment]
Hi! Did you run `pip install -r requirements.txt`?

**Comment by AmirMGhanem** [comment]
Ofcourse

**Comment by pinheiro-lucas** [comment]
Which OS are you using? We've made some tests into Ubuntu based and Windows 10.

**Comment by AmirMGhanem** [comment]
mac OS

**Comment by pinheiro-lucas** [comment]
Oh, that's the problem.. [Ursina Engine](https://www.ursinaengine.org/) doesn't has official support for MacOS. As our team don't have any device with this OS, we would be happy if you can contribute with the project giving this support. I would recommend you starting with requirements packages.

**Comment by AmirMGhanem** [comment]
"Ursina only supports Window's and Linux, but a virtual machine should do." 
only with VM.

**Comment by pinheiro-lucas** [comment]
That's sad =(
We're planning to change the game to JavaScript (the reason is to run as web game and no requirements needed).
I'll mark as closed as we can't provide support, fell free to ask or contribute with the project, we appreciate that.

**Comment by AmirMGhanem** [comment]
or maybe C# and unity

**Comment by pinheiro-lucas** [comment]
Yeah, C# would be the best option but that's not our stack

**Comment by AmirMGhanem** [comment]
Try Java and libGDX
